---
title: Knowledge Base (EloDocs)
sidebar_label: Knowledge Base
---

This section details the central developer portal onboarding references, guidelines, and translation parity tools.

## Completed Milestones

### Documentation Engine & Layout

- **Docusaurus Engine Integration**: Configured Docusaurus v3 as our central developer portal (EloDocs), providing a responsive documentation engine.
- **Custom MDX Component Pages**: Programmed custom MDX pages (e.g. Tools Workspace ecosystem, Studio Branding) to visual-explain monorepo architecture workflows.
- **Left Navigation Sidebars**: Implemented autogenerated context-based sidebars and structured paths for all sections, simplifying navigation structure.

### Localization & Translation Parity

- **Native Translation Pipelines**: Integrated i18n support, creating a dual locale structure (English source and Portuguese `pt-BR` translation copies) with translation parity protocols.

### CI/CD Deployment

- **Automated Root Compilation**: Integrated build tasks in the GitHub Actions workflow (`deploy-docs.yaml`) to compile and push both `CHANGELOG.md` and `ROADMAP.md` to the repository root.

## Planned Focus

- **Translation Verification Pipeline**: Automate the verification check to ensure 100% documentation sync.
- **API Auto-Generation**: Extract documentation blocks directly from Fastify routing controllers.
