name: elo-mcp

services:
  github:
    build:
      context: ./infrastructure/github
      dockerfile: Dockerfile
    container_name: elo-mcp-github
    restart: always
    env_file:
      - ./config/.env.github
    networks:
      - elo-mcp-net

  context7:
    build:
      context: ./infrastructure/context7
      dockerfile: Dockerfile
    container_name: elo-mcp-context7
    restart: always
    env_file:
      - ./config/.env.context7
    networks:
      - elo-mcp-net

  browser:
    build:
      context: ./infrastructure/browser
      dockerfile: Dockerfile
    container_name: elo-mcp-browser
    restart: always
    env_file:
      - ./config/.env.browser
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      - 'elo.internal:host-gateway'
    shm_size: '2gb'
    networks:
      - elo-mcp-net

  dockerhub:
    build:
      context: ./infrastructure/dockerhub
      dockerfile: Dockerfile
    container_name: elo-mcp-dockerhub
    restart: always
    env_file:
      - ./config/.env.dockerhub
    networks:
      - elo-mcp-net

networks:
  elo-mcp-net:
    driver: bridge
