name: elo-portal

services:
  portal-db:
    build:
      context: ./infrastructure/mongodb
      dockerfile: Dockerfile
    container_name: elo-portal-db
    restart: always
    ports:
      - '27018:27017'
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all', '--keyFile', '/data/mongo-keyfile']
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - elo-portal-mongo-data:/data/db
    networks:
      - elo-portal-network
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  portal-db-seed:
    build:
      context: ./infrastructure/mongodb
      dockerfile: Dockerfile
    container_name: elo-portal-db-seed
    # Sobrescreve o entrypoint para rodar o script de seed
    entrypoint: ['./seed.sh']
    depends_on:
      portal-db:
        condition: service_healthy
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      ADMIN_USER_SEED: ${ADMIN_USER_SEED}
      ADMIN_EMAIL_SEED: ${ADMIN_EMAIL_SEED}
      ADMIN_PASS_SEED: ${ADMIN_PASS_SEED}
    networks:
      - elo-portal-network

  portal-redis:
    build:
      context: ./infrastructure/redis
      dockerfile: Dockerfile
    container_name: elo-portal-redis
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - elo-portal-redis-data:/data
    networks:
      - elo-portal-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  elo-portal-network:
    driver: bridge

volumes:
  elo-portal-mongo-data:
  elo-portal-redis-data:
