name: Deploy Documentation

on:
  push:
    branches: [develop]
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-docs.yaml'
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PNPM Environment
        uses: ./.github/actions/setup-pnpm-env
        with:
          node-version: 22
          frozen-lockfile: 'false'

      - name: Generate Global Documents
        run: |
          pnpm github:generate:changelog
          pnpm github:generate:roadmap

      - name: Commit and Push Compiled Documents
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md ROADMAP.md
          if git diff --staged --quiet; then
            echo "No changes to CHANGELOG.md or ROADMAP.md"
          else
            git commit -m "docs: update root CHANGELOG.md and ROADMAP.md [skip ci]"
            git push
          fi

      - name: Build documentation
        run: pnpm docs:build
        env:
          DOCUSAURUS_BUCKET_URL: ${{ secrets.DOCUSAURUS_BUCKET_URL }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy docs/build --project-name=${{ vars.CLOUDFLARE_PAGES_PROJECT_DOCS }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
